name: Build SDK

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build using Gradle
        env:
          BANDWIDTH_URL_WEBRTC_SERVER: ${{ secrets.BANDWIDTH_URL_WEBRTC_SERVER }}
          BANDWIDTH_URL_WEBRTC_CONFERENCE_SERVER: ${{ secrets.BANDWIDTH_URL_WEBRTC_CONFERENCE_SERVER }}
        run: ./gradlew build
